"""Configuration constants."""

# Timeouts
PROCESSING_TIMEOUT_SECONDS = 60
PROCESSING_CHECK_INTERVAL = 2
REQUEST_TIMEOUT = 30

# Concurrency
MAX_CONCURRENT_UPLOADS = 5

# Retry settings
MAX_RETRIES = 3
RETRY_BACKOFF_FACTOR = 2
RETRY_STATUS_CODES = [429, 500, 502, 503, 504]
